### ISSUE TITLE
I think min level is not implemented correctly

### ISSUE THREAD

**Issue by altefwan** [Noxis-source/BG3-XP-Table-Generator#2]
I don't know if this is the expected behavior and I don't know the repercussions in the game but the program basically skips the levels below min level.

In any case, here is the scenario, I wanted to start the game a few levels higher, to give myself a boost but resume the progression normally after a certain level. From my experience (I tried setting the XP required to 0 before to test some builds but it didn't work, the level got stuck), setting the XP required to 1 for the levels you want to skip would be a solution.

I did some experimenting in excel and was able to find what I think is a viable formula.

From your code:
```
public void GenerateData(ICollection<XPDataRecord> source) {
    if (Progression == ProgressionType.Linear) {
        double limit = MaxLvl + 1;
        double sum = (limit - 1) * (limit / 2.0d);
        double root = MaxXP / sum;

        for (int i = MinLvl; i < limit; i++)
            source.Add(new XPDataRecord(i, Convert.ToInt32(i * root)));
    }
}
```

To:
```
public void GenerateData(ICollection<XPDataRecord> source) {
    if (Progression == ProgressionType.Linear) {
        double limitLow = MinLvl;
        double sumLow = (limitLow - 1) * (limitLow / 2.0d);
        double limit = MaxLvl + 1;
        double sum = (limit - 1) * (limit / 2.0d);
        double root = (MaxXP - MinLvl) / (sum - sumLow);

        for (int i = 1; i < MinLvl; i++)
            source.Add(new XPDataRecord(i, 1));

        for (int i = MinLvl; i < limit; i++)
            source.Add(new XPDataRecord(i, Convert.ToInt32(i * root)));
    }
}
```

I just converted the formula from excel and I wasn't able to test the code, so there might be some issues, but it should look something like this:
![image](https://github.com/Noxis-source/BG3-XP-Table-Generator/assets/110129872/341efcf3-5f9f-4776-865b-edc184638437)

**Comment by DmitryRomenskiy** [comment]
> I don't know if this is the expected behavior and I don't know the repercussions in the game but the program basically skips the levels below min level.

Yeah, that's intended. The idea here is to make it possible to redistribute XP for a certain level range. Say, I wish to keep default values for 1-5, but level up slower for the rest of it. It requires some manual work though.

I see your intention, looks ok. I'll make an update sometime probably soon.
